name: Auto Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Do Jest test
        run: bun run test -- --coverage
